[package]
name = "pulp"
version = "0.10.4"
edition = "2021"
authors = ["sarah <>"]
description = "Safe generic simd"
readme = "README.md"
repository = "https://github.com/sarah-ek/pulp/"
license = "MIT"
keywords = ["simd"]

[dependencies]
bytemuck = "1.12"

[features]
default = ["std"]
std = []
nightly = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
