[package]
name = "pulp"
version = "0.1.0"
edition = "2021"
authors = ["sarah <>"]
description = "Safe generic simd"
readme = "README.md"
repository = "https://github.com/sarah-ek/pulp/"
license = "MIT"
keywords = ["simd"]

[dependencies]
bytemuck = "1.12"
static_assertions = "1.1.0"

[features]
default = ["std"]
std = []
nightly = []
